# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ROSIE's BLOG
email: ronghua1990@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  To write down my understandings on exciting technologies.

# the subpath of your site, e.g. /blog
baseurl: ""
# url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username: rosie15

# Build settings
kramdown:
  input: GFM
  syntax_highlighter: rouge